### ISSUE TITLE
Passing a csl file to panzer

### ISSUE THREAD

**Issue by mhminai** [msprev/panzer#11]
An important part of styling is to define the csl file. After a quick search I was unable to see any document or example for using a csl file. Just wanted to know if and how specifying a csl file was supported using panzer.

I tried to put a csl field in my style, passing a path to the csl file I wish to use. However, the bibliography was still styled using pandoc's default styling. Setting the csl field in the metadata, using only pandoc does work.

I was unable to get the exact call to pandoc that panzer makes, but I did generate a DEBUG file. Am pasting the relevant (I think) sections below:

**Deleted the logs as I figured out the issue** please see below for more information

**Comment by mhminai** [comment]
Please do let me know if/how I can contribute. This "styling" mechanism is one of the things I am eagerly looking for to be comfortable with pandoc.

**Comment by mhminai** [comment]
Okay my bad, just read carefully and figured out that I have to use the `metadata` super field. Now the issue is that I would like my csl file to be in my .panzer directory. Maybe under a "csl" directory. Is that possible?

**Comment by mhminai** [comment]
Another related comment. For docx output, usually you need a "--reference-docx". Now that I have read the documentation 'more carefully'. I think this should be done with a "commandline"  superfield. Again I would like the reference docx to be common across all projects. i.e. ideally it should be in the panzer directory, could be within the templates subdirectory or its own.

**Comment by msprev** [comment]
Thanks for this! I'm glad that you sorted it out. You could also use a `commandline` idiom to set the csl file (pandoc supports setting the csl file via either mechanism).

On the directory for the csl file, there is nothing to stop one putting any path ones likes for the `csl` field, including a path to anything in `.panzer`. 

Here is some background rationale for why panzer doesn't assume this by default. The files in `.panzer` are related solely to the operation of panzer. csl files (like .bib files) can be used for many purposes (including with vanilla pandoc). It would not be good for panzer to assume that they are in `.panzer` -- by rights, they could be anywhere. You can say where they are, as I said above, in a style definition, and place them in `.panzer` if you like (I happen to do this with my css files, but I wouldn't assume that everyone should do the same).

The `--reference-docx` only relates to pandoc, and its proper place is in your `.pandoc` directory. If you place a file called `reference.docx` into `.pandoc`, this will be used by default (even without the `--reference-docx` argument). I believe, although I haven't checked, that pandoc will search for files listed in `--reference-docx` inside `.pandoc` first. As with the csl file, there is nothing to stop you specifying anywhere you like for your docx reference file (including somewhere in `.panzer`) in your panzer style definition.

I hope this makes sense.
