### ISSUE TITLE
local styles are note found

### ISSUE THREAD

**Issue by halloleo** [msprev/panzer#13]
I try using local styles, but `panzer` gives message:

```
ERROR:   No style definition found for style "fotext" --- ignoring it
```

I attached a zipped MWE. (You need to change the extension to `zip`, because GitHub only allows JPGs, not ZIP files.): [local-style-test_change-ext-to-zip.jpg](https://cloud.githubusercontent.com/assets/1521852/8247001/e822e360-168b-11e5-89e8-fc491ed25686.jpg)

The complete input and out when I run panzer is:

```
$ panzer -w latex -o out.pdf fotext-doc.md
WARNING: no global style definitions found
         ----- pandoc read -----
         pandoc reading with options:
           --smart
         ----- style definitions -----
         no global definitions loaded
         ----- document style -----
         style:
           fotext
ERROR:   No style definition found for style "fotext" --- ignoring it
         full hierarchy:
           empty
         writer:
           latex
         ----- run list -----
           empty
         ----- pandoc write -----
         running
$ 
```

**Comment by msprev** [comment]
Thanks for catching this. It's now fixed. Let me know if there are any problems.

**Comment by halloleo** [comment]
Strange things seem to happen, Mark:

Thanks for the fix. It _did_ work afterwrads. But now a day later I get the same error message again:

```
ERROR:   No style definition found for style "fotext" --- ignoring it
```

Is that possible? I haven't updated the source code again...

**Comment by halloleo** [comment]
Also, why does panzer look for style files only in `./styles` but not in the current directory `.` itself?

**Comment by msprev** [comment]
Thanks, but I can't reproduce the error with your original source files. panzer has not changed since the fix, so something in your source files or config must have changed to cause the error. Could you bundle them and upload them again for me to test?

I'm not sure that assuming any `.yaml` file inside `.` is a style definition file would be helpful, as you may want to keep other `.yaml` files there too. That is why the scope is restricted to `./styles/`. Can you give a use case where one would want to read from `.`?

**Comment by halloleo** [comment]
Sure, will bundle my test case when I'm back at home. I'm traveling right now, so that won't be before 3./4. July.

Re style files in the durrent directory: You have a point with other use of yaml files! It just would be convenient not to create a subfolder for simple documents. Maybe just the name styles.yaml under `.`?

**Comment by msprev** [comment]
Thanks. I'll wait until I get your files.

On the second issue, this is already implemented, but not documented as I was treating it as a legacy option. If there is no `styles/` directory found in `.`, panzer will attempt to look for a file called `styles.yaml` in `.` and read the local definitions from that. The same rules applies to global style definitions in `.panzer`. Does that address your case?

**Comment by halloleo** [comment]
Hey, that's great to be able to use a `styles.yaml` file in `.`.

Will let you know how I go when I'm back.

**Comment by halloleo** [comment]
Hi, finally tested this (with v1.00 now): Works beautifully! Thanks for fixing this.

**Comment by msprev** [comment]
Great, thanks!!
