### ISSUE TITLE
Suggestion: one-line pip install

### ISSUE THREAD

**Issue by BruceEckel** [msprev/panzer#18]
You can use pip to install directly from github

```
pip install git+https://github.com/msprev/panzer
```

**Comment by msprev** [comment]
Great, thank you! I didn't know that pip could do this. I'll update the documentation. 

One question: shouldn't it be `pip3` as panzer requires Python 3?

```
pip3 install git+https://github.com/msprev/panzer
```

**Comment by BruceEckel** [comment]
I only recently discovered it myself, and yes, it's a sweet feature.

Yes, pip3 makes sense if it's Python3 only. (I switched over to exclusively
Python 3 so I wasn't thinking about that).

PS: Just installed panzer today and I have high hopes, after struggling
with pandoc templates and latex.

-- Bruce Eckel
www.MindviewInc.com http://www.mindviewinc.com/
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com http://www.ScalaSummit.com

**Comment by msprev** [comment]
Thanks! I'm glad that you like it! Let me know if you have any problems. You might want to take a look at my dot-panzer repository as a starting point for hacking.

**Comment by BruceEckel** [comment]
Perhaps you can give me some advice. I'm creating a programming book from
pandoc-Markdown, distributing it as epub, mobi, and PDF. The PDF version is
not meant to be printed, so I want to use a single-sided format (like an
article), so it won't change from one page to the next. I'd like to use a
san-serif font for the headlines, and make them larger than usual (ideally
set them using a font size rather than \Huge). In addition, for the epub
and mobi I've got dingbats (images) next to the chapter titles, and also
the first-level subheads -- I don't know if it's possible to do that with
Latx.

I'd like to have headers and footers with separator lines, header/footer
text in (possibly smaller) san serif, and parts of the header/footer should
indicate the chapter and subsection.

Can you recommend something that gets me fairly close to that? I would
appreciate it ... I've been thrashing around with the PDF generation for
days now.

(If it would help, I can give you access to the Bitbucket repository)

-- Bruce Eckel
www.MindviewInc.com http://www.mindviewinc.com/
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com http://www.ScalaSummit.com

**Comment by msprev** [comment]
I'm not a LaTeX hacker, so can't advise on how to create this. But I'd suggest the following:
1. Get your layout right in LaTeX before messing around with pandoc. Once you have an example LaTeX document looking the way you like, it is easy to transform this into a pandoc template and then feed markdown through it.
2. Have a look at existing classes in LaTeX like memoir or koma-script. Folks have done a lot of work to develop good book layouts that you can build on.

Hope that this helps!
