### ISSUE TITLE
Default style

### ISSUE THREAD

**Issue by halloleo** [msprev/panzer#19]
Is there a name for a **default style** which (if it is defined in the `styles.yaml` file) is used when the document contains  _no_ style definition?

**Comment by msprev** [comment]
No, this was a deliberate design decision. If no style field is provided, then panzer does not attempt to apply a style definition.

You can easily define your own 'default' that you can assign explicitly. A natural arrangement is to have the default be the parent of any other style. I use a style called 'Base' as my default style; all my other styles derive from it.

**Comment by halloleo** [comment]
Mmmmhhhh, can my own ‘default style' get used by documents which have no style definition. That would be so great!

**Comment by msprev** [comment]
A workaround is that you can invoke panzer with `panzer source.md --metadata=style:Base`?

The right default, if the style field is missing, is for there to be no style!

**Comment by halloleo** [comment]
Unfortunately that is not at all a work around: Because when you set `--metadata=style:default` on the command line the document cannot override this anymore. :-( A default style should be overridable by any given style, don’t you think so?

**Comment by msprev** [comment]
You got me there. I still think that no style should be applied unless one is specified...
