### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by tubia** [msprev/panzer#2]
Hi,
I'll try to run `python3 setup.py install` but It throws an error:

``` bash
python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'
```

Python 3 version:

``` bash
python3 --version
Python 3.4.0
```

**Comment by tubia** [comment]
Package dependency problem.  
The solution is to install `setuptools` for Python 3. For debian-based distros use:

```
sudo apt-get install python3-setuptools
```

Maybe this could be added to the README?

**Comment by msprev** [comment]
Thanks! Now fixed!

**Comment by tubia** [comment]
Thank you @msprev :)
