### ISSUE TITLE
Running filter gives ERROR: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by mhminai** [msprev/panzer#22]
When I run a filter with pandoc, it works fine, when I use it via panzer it fails with the following error:
ERROR: [Errno 13] Permission denied

The filter is at: https://gist.github.com/bpj/f591a9e29fe974fa791f#file-pandoc-collect-floats-py

MWE:

```
# This is a test

Before the table

|A|B|C|
|-|-|-|
|1|2|3|

After the Table

TablesHere
```

Running with `pandoc test.pdc --filter ~/.panzer/filter/collect_floats/collect_floats.py -o test.docx` works file but when I do `panzer test.pdc --filter ~/.panzer/filter/collect_floats/collect_floats.py -o test.docx`, it gives me:

```
     ----- pandoc read -----
     running
     ----- style definitions -----
     global:
       AamjStyle     AddLatexRefs  AomjStyle     ApaStyle       Article
       Base          BiblatexPdf   Book          BookReview     Braindead
       CIM           CV            ChadStyle     Draft          JlosStyle
       LeadJouStyle  Letter        LodjStyle     MthemePres     Mumford
       Notes         NotesSans     PanCite       Plain          PropStyle
       RefAOM        RefAPA        RefAPA_nodoi  ReferJournals  Story
       Work
     ----- document style -----
     no "style" field found, run only pandoc
     writer:
       docx
     ----- run list -----
     filter:
      1  collect_floats  "~/.panzer/filter/collect_floats/collect_floats.py"
     ----- filter -----
     [1/1] collect_floats docx
ERROR:     [Errno 13] Permission denied
     ----- pandoc write -----
     running
```

My usecase is to apply this filter only with certain styles.

**Comment by msprev** [comment]
I believe this is because your filter, `encode_floats.py`, does not have its executable permission set. panzer won't run it unless this permission is set. Strangely, pandoc will execute a filter even if the filter is not executable. This looks like a bug to me, so I'm pinging @jgm.

Could you please try running `chmod +x encode_floats.py` and then rerun? It works fine for me here.

**Comment by jgm** [comment]
+++ Mark Sprevak [May 07 16 01:58 ]:

>   I believe this is because your filter, encode_floats.py, does not have
>   its executable permission set. panzer won't run it unless this
>   permission is set. Strangely, pandoc will execute a filter even if the
>   filter is not executable. This looks like a bug to me, so I'm pinging
>   [1]@jgm.

It's intentional.  Just as you don't need `script.py` to be executable
to do `python script.py`, so you don't need this to do `pandoc -F
script.py`.

**Comment by msprev** [comment]
Fair enough. I'll try to think of a way for panzer to mimic this behaviour. Might not be easy as I think not executing non-executable files is baked into the Python subprocess module.

**Comment by mhminai** [comment]
Confirming that changing the permissions works fine.

Thanks again for a great tool. I use it quite extensively. Plan to
contribute when I get some time. Should hopefully submit my thesis in
August and then shall try and add some of the learnings I have using panzer.

Thanks and Regards,
Mohammad Haris Minai

**Comment by msprev** [comment]
Thank you! Any PRs would be welcome and I'm happy to plan potential PRs with you. Good luck with the thesis.

**Comment by msprev** [comment]
I'm closing this issue for the moment. From what I can see, there is no way to get Python's subprocess to execute a file whose execute permission is not set. I'll add some information to the documentation on this.
