### ISSUE TITLE
Command line option "--verbose" for pandoc not recognized by panzer?

### ISSUE THREAD

**Issue by mhminai** [msprev/panzer#26]
I tried to use the `--verbose` option with panzer, it continues after throwing an error:
```
ERROR: do not recognize command line option "--verbose"---ignoring
```

This option is recognized by the bare `pandoc` command.

I was expecting panzer to pass this option to the invocation of pandoc

panzer version: 1.0
pandoc version: 1.17.0.2

**Comment by msprev** [comment]
Thank you for catching this. It should be fixed now in the latest commit. Please let me know if you have any problems.
