### ISSUE TITLE
Feature request: ---pandoc PATH/TO/EXECUTABLE and/or check PANDOC_PATH env variable

### ISSUE THREAD

**Issue by bpj** [msprev/panzer#30]
I just decided to be crazy enough to try a [pandoc-nightly][] build to work around a bug in the stable release of Pandoc, but found that unless I'm not also crazy enough to drop it into `~/bin/` under the name `pandoc` I can't use it with panzer! What about adding a `---pandoc PATH/TO/EXECUTABLE` option and/or check the `PANDOC_PATH` environment variable like [Pandoc-Wrapper][] aka `Pandoc.pm` does[^1]?

Personally I would be perfectly happy with the env variable, but Windows users might not agree!

(I could also do some symling shenanigans which is what I in the end did, but moving around/renaming symlinks isn't any more fun than renaming/moving around executables in the long run!)

[^1]: By my suggestion I have to admit, at that time because I used a wrapper script. In principle you could make `Pandoc.pm` invoke `panzer`!

[pandoc-nightly]: https://github.com/pandoc-extras/pandoc-nightly/releases
[Pandoc-Wrapper]: https://github.com/nichtich/Pandoc-Wrapper/

**Comment by msprev** [comment]
This is a good suggestion and was relatively easy to implement. I've added a `---pandoc` command line option as suggested that allows you to specify a pandoc executable. It's now in the latest commit. Please let me know if you have any problems.

**Comment by bpj** [comment]
Thanks!
