### ISSUE TITLE
Support Pandoc pptx writer

### ISSUE THREAD

**Issue by kbro237** [msprev/panzer#34]
As of 2.0.5 `pandoc` has a PowerPoint [writer](https://github.com/jgm/pandoc/commit/da4703236dbef86dd7fa036fb28fa43039e45146). I'm guessing it needs to be identified in `panzer` as a binary format because I'm getting an error about it looking for a default template.

Note: this is not a particularly urgent fix for me -- it's not a very useful writer yet.

**Comment by msprev** [comment]
Thanks! This was on my todo list. I've updated it for pandoc 2.0.5 now. Let me know if there are any issues.
