### ISSUE TITLE
Running filter on Windows gives ERROR [WinError 193] "%1 is not a valid Win32 application"

### ISSUE THREAD

**Issue by josineto** [msprev/panzer#36]
On Windows (10 x64), trying to run python filters on [dot-panzer](https://github.com/msprev/dot-panzer) always gives me `ERROR [WinError 193] %1 is not a valid Win32 application`. For instance, for a filter named `smallcaps` and output type set to `html5`, the following lines return:

    [1/3] smallcaps html5
    ERROR:     [WinError 193] %1 is not a valid Win32 application

I guess `%1`, in this case, is `html5`. All python filters result in the same error. The location of each filter, printed in command line, is correct. I tried these things, all unsuccessful:

* run `chmod +x` on filter (using `Git Bash` on Windows)
* change first line of filter, from `#!/usr/bin/env python3` to `#!c:\users\netot\appdata\local\programs\python\python36-32\python.exe`
* change filter name to `./<filter>`:
  - move filter to current directory
  - run `chmod +x` on filter
  - change first line as above
  - change filter name to `./<filter>` on `styles.yaml`

My `styles.yaml` is like following (for filter named `smallcaps.py`:

    Base:
      all:
        filter:
          - run: ./smallcaps.py

I think I'm doing something wrong here... Python is on the path, and I can run a postflight bat script (similar to bash script on Linux) successfully (though I have to write path separators as `\\` in `styles.yaml` for this bat file).

**Comment by msprev** [comment]
I'm not entirely sure what is going on here as I don't have a Windows 
machine to test. The first thing is to check if this is an issue 
specific to the filter or to panzer. Can you try invoking the filter 
using just vanilla pandoc (i.e. using pandoc's `--filter` command line 
option)?

**Comment by josineto** [comment]
Vanilla pandoc works fine with the filter: no error at all, and the filter behaviour is as expected. I'm using Python 3.6.4, 32 bits, in Windows 10, 64 bits. Do you think it could be related with 32/64 mix?

**Comment by msprev** [comment]
The 64/32 bit mix could be causing the issue. There is a report that Python on Windows doesn’t like this:

https://stackoverflow.com/questions/5538671/python-call-to-external-program-results-in-error-193-1-is-not-a-valid-win32-a

Can you try a pure 64 bit or pure 32 bit setup for Python?

**Comment by josineto** [comment]
I've installed Python x64 (after uninstall and completely clean Python 32 bit installation), repeated all the things in my first comment, and again, got `ERROR [WinError 193] %1 is not a valid Win32 application`...

In the link you cited, the main answer was passing the script handler to `call()`, instead of the script itself. In the second comment of that answer, there's an example: `call(["cscript.exe","<myfile>"])`, assuming `cscript.exe` is the script handler. I don't know Python, but perhaps that answer could help here too.

**Comment by msprev** [comment]
Good. The next thing to check is that the filter is an executable. Try going to the directory where the filter is and typing its name ‘smallcaps.py’ at the command line. Does it try to run the filter?

See this on making Python scripts on Windows executable:

- https://stackoverflow.com/questions/4235834/how-to-make-python-scripts-executable-on-windows#4235923

**Comment by josineto** [comment]
Sorry, I forgot to answer here. In the first attempt to run just `smallcaps.py`on its own directory, the command-line said that it was unable to load app that was on shebang (using other words). Then I changed the first line of `smallcaps.py` from `#!c:\users\netot\appdata\local\programs\python\python36-32\python.exe` to `#!c:\users\netot\appdata\local\programs\python\python36\python.exe` (directory of Python x64). Now the script runs when called in its own directory, but keeps showing the same error in panzer, as other python filters also do. (I haven't tried other filters than those used in `dot-panzer` repository)

**Comment by msprev** [comment]
The problem is that Windows is telling panzer that this filter is not executable for some reason. Let's check that the association is correct for this filetype... Try this:

```
C:\>assoc .py

C:\>ftype Python.File
```

And see what it reports back...

As a possible fix, you could explicitly point it to the executable by doing this:

```
Base:
  all:
    filter:
      - run: "`c:\users\netot\appdata\local\programs\python\python36\python.exe smallcaps.py`"
```

**Comment by josineto** [comment]
Running the commands gives the following:

~~~~shell
C:\>assoc .py
.py=Python.File

C:\>ftype Python.File
Python.File="C:\WINDOWS\py.exe" "%L" %*
~~~~

I checked if that executable is really on that directory, and it is there.

I tried your fix, without success. Tried to put `smallcaps.py` in all these locations:

* current directory where panzer is run
* `c:\users\netot\appdata\local\programs\python\python36\`
* and, of course, panzer's default filter location

This time, I got `ERROR: [WinError 2] The system cannot find the file specified`, no matter which of the options below I follow (I needed to double backslash anyway):

~~~~yaml
- run: "`c:\\users\\netot\\appdata\\local\\programs\\python\\python36\\python.exe smallcaps.py`"
or
- run: "`c:\\users\\netot\\appdata\\local\\programs\\python\\python36\\python.exe .\\smallcaps.py`"
or
- run: "`py smallcaps.py`"
or
- run: "`py .\\smallcaps.py`"
~~~~

**Comment by msprev** [comment]
I've been doing a bit of reading about this. What it is clear is that when panzer calls out to the filter script it does not know that the filter is an executable. Somehow this information about the associations of .py files on the command line is not available to running programmes calling out using subprocess. Unless you are using cygwin, windows has no shebang support, so this information in the external script is meaningless.

So... it looks like the only solution on Windows is to force subprocess to run the external process via the shell. This is not usually recommended or necessary under unix. But it looks like it might be needed to get around this issue on Windows. 

I've pushed a version with appropriate changes. See if it works with the normal panzer setup:

```
Base:
  all:
    filter:
      - run: smallcaps.py
```

**Comment by josineto** [comment]
**It works!** I had to revert all shebangs to default `#!/usr/bin/env python3`, or use real Python dir, and all worked fine! The expected behaviour of the filters is correct too! Thank you!!!

*Just by curiosity*: I've tried to run lua filters (I know they're not supported by panzer) using following setup:

~~~~yaml
Base:
  all:
    filter:
      - run: "`pandoc -s -f json -t json --lua-filter myfilter.lua`"
# also tried with -f native -t native, without --lua-filter option and without -s, with similar result
~~~~

which gave me this result:

~~~~
Traceback (most recent call last):
  File "C:\Users\netot\AppData\Local\Programs\Python\Python36\Scripts\panzer-script.py", line 11, in <module>
    load_entry_point('panzer==1.3.1', 'console_scripts', 'panzer')()
  File "c:\users\netot\appdata\local\programs\python\python36\lib\site-packages\panzer\panzer.py", line 68, in main
    doc.pipe_through('filter')
  File "c:\users\netot\appdata\local\programs\python\python36\lib\site-packages\panzer\document.py", line 509, in pipe_through
    stderr = stderr_bytes.decode(const.ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 31: invalid continuation byte
~~~~

Is it somehow possible? It seems that panzer pipes conversion through filters (please sorry if I'm wrong), so I thought pandoc could act as a filter too... Thank you anyway!

**Comment by josineto** [comment]
(For the question on previous comment) I realized, by reading README, that the correct syntax would be:

~~~~yaml
- run: pandoc
  args: "`-f json -t json`"
~~~~

But this turns into `pandoc html5 -f json -t json` (supposing `html5` as final writer), because the first argument to filters is always the writer name. This crashes, because pandoc tries to open a file named `html5`. If the writer argument could be turned off for particular filters, perhaps lua filters could be supported this way. Should I open an issue on this, or lua filters definitely would not be supported?

**Comment by msprev** [comment]
I'm afraid that this very much falls under the heading of 'not supported'. pandoc's new lua filters cannot be run this way. 

I could add support for lua filters but the downside is they would run slower than standard json filters negating much of the motivation for using them. I'd suggest that if there are any lua filters you want to use then modify their code to consume and emit json and so turn them into a standard json  filter.

**Comment by msprev** [comment]
Ok -- I caved and implemented a way to run lua filters. It's in the latest commit (v1.4 of panzer). 

This will work best if you plump for either all lua or all json filters. It won't be ideal in a mixed workflow (some lua some json filters) as lua filters will always be run first. This is for performance reasons -- lua filters are run fast. If you have a mixed workflow with some lua some json and you want to intersperse your application of lua and json filters to a doc, I'd suggest rewriting to use either all lua or all json filters (it's trivial) so you can apply them in any order you like.

**Comment by josineto** [comment]
I tried a bunch of lua filters, but none of them got expected behaviour. In fact, it seems that lua filters are receiving JSON, when should receive AST instead (according to [pandoc's documentation](https://pandoc.org/lua-filters.html)). But even here I couldn't realize how to do any filtering in the lua filter... I will open a issue on this.
