### ISSUE TITLE
Test suite errors

### ISSUE THREAD

**Issue by jgclark** [msprev/panzer#37]
I've just installed panzer, and thought I'd run the test suite on both 'pandoc' and 'panzer' supplied test files.

On each of the 130+ tests, for both remits, it gave this error:  `ERROR:   do not recognize command line option "--smart"—ignoring`.

**Comment by msprev** [comment]
Thanks for this prompt. The test suite is out of date and was not fully implemented. It’s a sound idea I think but not currently ready for release. I need to remove it from the release branch and will do so.

**Comment by msprev** [comment]
Now moved to separate branch and out of master. Thanks!
