### ISSUE TITLE
--katex, --mathjax, etc. with URL argument

### ISSUE THREAD

**Issue by wtraylor** [msprev/panzer#39]
Some commmandline arguments of pandoc have an *optional* URL argument, i.e. they can be boolean switches (with default URL) *or* require an argument.
For example `pandoc --katex` and `pandoc --katex=/home/user/katex` both work.

In panzer, it works to add `katex: true` to the the YAML style definition, but `katex: /home/user/katex` does not work.

Though I didn’t test it with all of the ones below, I guess it is an issue with this list of parameters, too:

- `katex`
- `mathjax`
- `webtex`
- `latexmathml`

Thanks for writing this nice piece of software!

EDIT: I’m sorry, this was my own mistake. The correct way to declare the path for e.g. katex is this:
``katex: "`/home/user/katex`"``

**Comment by msprev** [comment]
Thanks – yes the syntax is because pandoc (and hence panzer) otherwise interprets the value of yaml fields as markdown. I want 100% compatibility with pandoc here so that users can cut and paste fields freely between invocations of panzer and pandoc.
