### ISSUE TITLE
Local style.yaml files

### ISSUE THREAD

**Issue by jgrizou** [msprev/panzer#4]
It seems currently we can define style in .panzer/styles.yaml or locally in the yaml header.

It would be nice to be able to provide a path to a styles.yaml file that is local to our project, e.g.

```

---
stylepath: "`path/to/project/styles.yaml`"
style:MyTemplate

---
```

Any thoughts on this?

**Comment by msprev** [comment]
It's an interesting idea. But you can do something very close to this already though. Let me know if this solves the use case. Embed whatever you want in your local styles.yaml file in a `styledef` field of a separate file, `local_styles.yaml`: 

```
---
styledef:
    CONTENT OF YOUR LOCAL STYLES.YAML
---
```

then just run `panzer local_styles.yaml input.md -o output.html`. The `styledef` will be shunted into `input.md`'s AST.

The downside is if you _also_ want to use `styledef` inside `input.md`. Its content would  be clobbered by the entry in `local_styles.yaml`, as pandoc will combine them with a left biased union.

**Comment by jgrizou** [comment]
Yes that is a good option but, if I understood well, the downside is very major.

Having all styles in one file in one location can be a hurdle when managing several projects with different styles. You end up with a big .panzer/styles.yaml file and, more importantly, the project is not self contained.

Don't bother too much with all my comments, I am just starting. Once I get familiar with the code I could try this myself ;)

**Comment by msprev** [comment]
Doesn't the suggestion solve this? Just stick whatever you want defined in `local_styles.yaml` and add it to the command line before your input file? You can have as many `local_styles.yaml`s as you like, and keep them wherever you like? It's equivalent to sharing `styledef`s across your markdown files.

Is your concern that, even with this, you want to customise/add to the style definitions inside each of your markdown files too?

Here is possible solution. How about panzer looks for a local `styles.yaml` in the working directory. If found, this would override the global `styles.yaml`. This would be consistent with the current behaviour for filters, scripts, and templates.

**Comment by jgrizou** [comment]
Yes my concern is what you pointed out, I still want to customize the styledef inside each markdown.

Having the same behavior as filters, scripts, etc is a nice and consistent solution!

About this, why not having a `path:` option for filter, scripts, templates fields such that panzer checks that path first?

```
---
filter:
  path: ./custom/path/to/filters
  -run: filter1.py
  -run: pandoc-citeproc
---
```

In order panzer would look for:

| # | look for |
| --- | --- |
| 1 | ./custom/path/to/filters/foo.py |
| 2 | ./foo.py |
| 3 | ./filter/foo.py |
| 4 | ... |

**Comment by msprev** [comment]
I'll implement looking for a current working directory `styles.yaml` as this seems to fit nicely with current behaviour for filters, templates, and scripts.

I'm not sure about the `path:` field. It's possible to implement, but would require a bit of thought to do it right. I'm not yet convinced it is worth it. 

Here is one final workaround for your problem. It sounds like you really want a dedicated `.panzer` directory (styles, filters, etc.) for each project. You can do this via panzer's command line `---panzer-support` option. You pass the path to your custom `.panzer` directory. You could in principle have a custom `.panzer` directory for every project, and place it wherever you like. If you want to share items between these `.panzer` directories (say, templates), you can do this via symbolic links. Does this solve the problem?

**Comment by jgrizou** [comment]
Yes, this address my concern perfectly!  Sorry about that, I didn't notice this feature before.

**Comment by msprev** [comment]
Great. I'll close this issue for the moment. I've added to my todo list to implement local `styles.yaml` files.

**Comment by msprev** [comment]
I've implemented some changes that you may like. `styles.yaml` is no longer a magic filename. panzer instead reads style definitions found inside any yaml files -- first searched for in `.panzer/styles/` then searched for in `./styles/`. This should give you the flexibility you are looking for. I've updated the documentation to reflect this change. 

The old method of defining styles in a single `styles.yaml` file in `.panzer/` is still supported for legacy reasons.

**Comment by jgrizou** [comment]
Great, it is exactly what I was dreaming of, I think it brings more flexibility. Thanks!

One really dumb comment: the folder for filters and templates are called "filter" and "template" at the singular. For styles it is plural.

**Comment by msprev** [comment]
Thanks. I noticed that too. I think it is the best that can be done in terms of naming.
