### ISSUE TITLE
Is it possible to relocate .panzer directory?

### ISSUE THREAD

**Issue by jgclark** [msprev/panzer#40]
As far as I can see from the documentation, the `~/.panzer` directory location for supporting scripts and styles is hard-coded. There are situations where you'd want multiple users to share the same files, and (in my case) the same user over several machines. Ideally I'd like to relocate this to sit in my Dropbox. I can probably do so with links, but if it's possible within panzer itself, that would be much better.

**Comment by msprev** [comment]
Yes, this is available as a command line option. Please read the documentation: https://github.com/msprev/panzer#use
