### ISSUE TITLE
What do you think of Pandoctools

### ISSUE THREAD

**Issue by kiwi0fruit** [msprev/panzer#41]
What do you think of [Pandoctools](https://github.com/kiwi0fruit/pandoctools): profile manager of text processing pipelines (uses Pandoc filters and any text CLI filters)?

**Comment by msprev** [comment]
This looks interesting -- it looks like a nice tool! The reproducibility problem is a big and important one. It's good to see this being addressed.

**Comment by kiwi0fruit** [comment]
Thanks for response! Today I've learned about your Panzer. And it seems that you tried to solve alike problem that I did (but differently). So I was interested in your opinion.

**Comment by msprev** [comment]
I didn't do much on the reproducibility front -- it was more to add an extra layer of abstraction ('styles') so an individual user doesn't need to remember a million settings for document compilation via pandoc. They can just set one metadata value (`style: Article`) and forget about it. Or they can combine 2 styles (`style: [Article, BoldHeadings]`)

I didn't do much work though on how to reproduce the workflow produced by styles in a reliable way between users. Doing this properly means tracking all the dependencies of all programs invoked in document compilation, which (as you know!) is really hard.

**Comment by kiwi0fruit** [comment]
I see. I didn't mind to dig into command line arguments at all so I went another way. I was irritated by copy-pasting terminal commands, adjusting names and like. So it's not a reproducibility that inspired me. I also needed extra level of abstraction. But I've chosen the one that is the easiest to understand it's workings and to tune in a moment.

Reproducibility came next. But I don't really track versions - I simply hope that they won't break anything and simply add used Pandoc and text filers to dependencies of python module.

**Comment by kiwi0fruit** [comment]
You even have `preflight` and `postflight` options: this functionaliy together with filters themselves is what I initially wanted to put into some kind of profiles. So this ended with bash scripts that define everything.

But in your case it's metadata section that controls panzer app.

**Comment by kiwi0fruit** [comment]
### Markdown+HTML as PDF, MS Word and others killer

@msprev See the [**dream description**](https://github.com/kiwi0fruit/misc/blob/master/pdf_and_word_killer.md).
