### ISSUE TITLE
Ability to select default writer in style

### ISSUE THREAD

**Issue by m42e** [msprev/panzer#44]
Hi,

I really like panzer a lot, and I have looked around for a while but could not find a way to specify the default writer in the style. Didn't I get it or is there no such option available?

IMHO this would be helpful (especially in the case you have to select the latex output for example, but with postprocessing you get a pdf anyway) and will also reduce characters to type and remember for calling panzer.

Matthias

**Comment by msprev** [comment]
Thank you for the kind comments! I'm not entirely sure what is meant by a default writer. There is `all` in the style definitions which applies certain settings to every writer. It was a deliberate design decision to keep the writer and reader as explicit command line arguments to panzer, not part of the style definition. A style definition should say, 'given this writer has been invoked on the command line, which pandoc options should I apply'. 

If you want to automate invocation of pandoc/panzer in the way you suggest, you need something simpler like an alias or bash wrapper script that always calls it with a certain writer command line argument.
