### ISSUE TITLE
Creates ~/.panzer even though using ---panzer-support

### ISSUE THREAD

**Issue by dnebauer** [msprev/panzer#45]
I've moved the panzer configuration files from `~/.panzer` to `~/.config/panzer`. Even if I use the `---panzer-support` option to specify `~/.config/panzer` as the support directory (as per the [Use](https://github.com/msprev/panzer#use) instructions and #40), panzer insists on creating the `~/.panzer` directory template anyway:

```
$ panzer ---panzer-support="/home/user/.config/panzer --to="html" --output="test.html" "test.md"
WARNING: default panzer support directory "/home/user/.panzer" not found
WARNING: create empty support directory "/home/user/.panzer"?
    Press Enter to continue...
```

Despite panzer's temporary obsession with `~/.panzer` at the start of processing, it uses the nominated support directory for actual document processing.

Can this check for, and creation of, the default support directory be skipped when the `---panzer-support` option is used?

**Comment by msprev** [comment]
Thank you for this bug report. I've pushed a fix now. Let me know if there are any problems!

**Comment by dnebauer** [comment]
Fix works great. Thanks.
